### ISSUE TITLE
Add automatic deploy and pyup bot

### ISSUE THREAD

**Issue by jettify** [aio-libs/aiosparql#22]
1) Most of projects has this feature so each team member can trigger deploy with git tag, should be easy to do
2) we use pyup bot to watch updates in dependencies, very useful tool to find incompatibilities.

**Comment by asvetlov** [comment]
I not very happy with pyup.
It prevents conflicts but generates too many PRs.
As an alternative we could just enable nightly builds on travis (relative new feature).
It could detect compatibility problems as well without too annoying merges.
Not sure which way should we choose but I like to try both

**Comment by jettify** [comment]
We can enable bot to do updates each month.

**Comment by asvetlov** [comment]
Each month is too long probably, what's about each week?
Please point me on pyip doc page for this parameter.

**Comment by jettify** [comment]
This is just yaml file https://pyup.io/docs/bot/config/

**Comment by cecton** [comment]
I know it is a great improvement but I don't have much experience about this so I will apply the decision you guys agree on.

**Comment by asvetlov** [comment]
I'll do it.

**Comment by asvetlov** [comment]
Fixed. 
Changed `README.md` to `README.rst`, dropped invalid `aiosparql.version_info` (was not compatible with https://www.python.org/dev/peps/pep-0440/ added long description, tests added to tarball etc.

New release should be published by adding git tag (`git tag -a v0.10.0` for example) and pushing it.
Travis builds tarball and wheel automatically.
Please use `v<version>` tags -- it is recommended by git and automatic packagers do use this format.

Feel free to ask if you have any question.

**Comment by cecton** [comment]
Thanks a lot @asvetlov
