### ISSUE TITLE
Release v0.10.0

### ISSUE THREAD

**Issue by cecton** [aio-libs/aiosparql#31]
I think we are good for a new alpha release at this point. Can you show me how you normally do that?

Thanks

**Comment by asvetlov** [comment]
I'll make a document for describing release procedure.

**Comment by asvetlov** [comment]
@cecton I suggest you merge PR and try to make release yourself to check if the document is correct.

**Comment by cecton** [comment]
@asvetlov I did follow the procedure but the version 0.10.0 was already on PyPi....  Any idea what happened?

**Comment by cecton** [comment]
Oh I see, the file has been uploaded by Travis. Okay that's easier.

**Comment by cecton** [comment]
Thanks for everything @asvetlov :)

**Comment by asvetlov** [comment]
Sure :)
I did several 0.10.0aX releases while tested travis deployment.
Uploading alphas and betas is safe, pip don't  install them without `--pre` key.
