### ISSUE TITLE
Add `async with` to open and close automatically the SPARQLSession

### ISSUE THREAD

**Issue by cecton** [aio-libs/aiosparql#34]
In the previous versions we had the possibility of using `async with` but it's now not possible anymore (because we removed the inheritance from `ClientSession`). We should implement it to make the code easier to write for the developers.

**Comment by asvetlov** [comment]
Not very hard to do.
`aiohttp._RequestContextManager` is too hairy for Python 3.4 support, 3.5+ version could drop many gory details.

**Comment by cecton** [comment]
Cool thanks a lot! I keep this ticket like a todo for the future improvement. I don't have much time at the moment for anything unfortunately.

**Comment by cecton** [comment]
Inactive, closing
