### ISSUE TITLE
Looking for the project maintainer

### ISSUE THREAD

**Issue by asvetlov** [aio-libs/aiosparql#40]
@cecton, the project initial author, doesn't use Python anymore.
She is not interesting for `aiosparql` project support.

I never used sparql personally and overwhelmed by other Open Source projects.

The library is looking for a project maintainer.
The responsibility is not too high, maybe the biggest challenge for now is keeping the support of the newest Python and aiohttp versions.

I can help with any question, CI setup, etc. but really love to have the project owner who is responsible for communication with users and keeping updates working.

If somebody wants to be a champion -- please left a comment.

**Comment by cecton** [comment]
I will also help for the transition and I will maintain it until we find someone. I believe my ex-colleagues at TenForce might be also interested as it initiated from there. Maybe @lordblendi @nvdk you can ping everybody who might be interested? Thanks a lot

**Comment by lordblendi** [comment]
@bertvannuffelen or @langens-jonathan maybe?

**Comment by asvetlov** [comment]
The invitation is sent to @AtomsForPeace. If somebody else wants to join -- please let me know.

I've installed dependabot GitHub application, it will help to keep all dependencies up-to-date.
The project uses Travis CI for tests and deployment, https://github.com/aio-libs/aiosparql/blob/master/RELEASE_PROCEDURE.rst contains instructions for making a new release.

Let's make a release soon, roughly after managing dependencies update.

**Comment by AtomsForPeace** [comment]
Went through the steps but got the following error on deploying:
HTTPError: 403 Client Error: Invalid or non-existent authentication information. for url: https://upload.pypi.org/legacy/
Any ideas?

**Comment by asvetlov** [comment]
Perhaps something is outdated. Please ping me tomorrow.

**Comment by cecton** [comment]
@AtomsForPeace you can join the gitter channel of aio-libs if you want, the whole team is there

**Comment by asvetlov** [comment]
@AtomsForPeace I've updated PyPI password to use token-based authentication.

Just checked [0.11.0a1](https://pypi.org/project/aiosparql/0.11.0a1/) version release (initiated by pushing git tag). 
Everything looks fine.
Please feel free to contact me in case of any questions.

**Comment by AtomsForPeace** [comment]
Thanks. Will close this now I guess

**Comment by asvetlov** [comment]
We still need a release, isn't it?

**Comment by AtomsForPeace** [comment]
I'll try again now

**Comment by AtomsForPeace** [comment]
New release made. Thanks

**Comment by asvetlov** [comment]
Cool!
I've deleted accidental v0.11.1 and v0.11.1aX tags from github.
Please make sure that you have no such tags in your local copy.

**Comment by cecton** [comment]
@AtomsForPeace I just added you on Twitter. Don't hesitate to reach me whenever you want
